#!/usr/bin/bash
# use: git config core.hooksPath .gitHooks

# availability of python
py=$(which python || which python3 || which py)
if [[ -z $py ]]
then
  echo "No python found"
  exit 0
fi

# go to the root of the git repo
cd $(git rev-parse --show-toplevel)

# path to sompy python scripts
sompy=$(pwd)/submodules/sompy/somutil

all=()
mdjs=()
svgs=()
txts=()

for file in $(git diff-index --cached --name-only HEAD); do
  if [[ -f $file ]]
  then
    all+=($file)
    if [[ $file == *.mdj ]]; then mdjs+=($file)
    elif [[ $file == *.svg ]]; then svgs+=($file)
    else txts+=($file)
    fi
  fi
done

if [ ${#mdjs[@]} -gt 0 ]; then
  echo cleaning mdj files
  $py $sompy/cleanMdj.py -l ${mdjs[@]}
fi
if [ ${#svgs[@]} -gt 0 ]; then
  echo cleaning svg files
  $py $sompy/cleanSvg.py -l  ${svgs[@]}
fi
if [ ${#txts[@]} -gt 0 ]; then
  echo cleaning text files
  $py $sompy/cleanTxt.py -l ${txts[@]}
fi

for file in ${all[@]}; do git add $file; done
